# Generated by Django 3.1.4 on 2021-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Timer', max_length=100, null=True)),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('sec', models.PositiveIntegerField(blank=True, null=True)),
                ('sound', models.CharField(choices=[('0', '終了音'), ('1', '開始音'), ('2', '音声なし')], default=0, max_length=100)),
            ],
        ),
    ]
