# Generated by Django 3.1.4 on 2021-08-26 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Timer', max_length=100, null=True)),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('sec', models.PositiveIntegerField(blank=True, null=True)),
                ('sound', models.CharField(choices=[('0', '終了音'), ('1', '開始音'), ('2', '音声なし')], default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Timer', max_length=100, null=True)),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('sec', models.PositiveIntegerField(blank=True, null=True)),
                ('sound', models.CharField(choices=[('0', '終了音'), ('1', '開始音'), ('2', '音声なし')], default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='タイトル', max_length=100, null=True)),
                ('set', models.CharField(default='', max_length=1000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
