# Generated by Django 3.1.4 on 2021-08-16 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hour', models.IntegerField()),
                ('min', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('sec', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
            ],
        ),
    ]
